<?php
/**
 * Newspack Insights — Subscribers section (NPPD-1616).
 *
 * Subscribers tab scope: paid subscriber base health for non-donation
 * subscription products. Active subs, MRR/ARR, new/churned counts,
 * revenue (gross/net/refund rate), tenure distribution, upcoming
 * renewals, failed payment retry rate, per-product performance, and
 * cancellation reasons. Local-DB-driven (WooCommerce HPOS or legacy
 * CPT); does NOT need BigQuery.
 *
 * Wiring:
 *  - Loads the Tab 6 PHP classes (storage interface, two backend
 *    implementations, donation classifier, metric orchestrator, REST
 *    controller).
 *  - Registers the `newspack-insights/v1/subscribers` route via
 *    {@see Insights\Subscribers_REST_Controller}.
 *
 * @package Newspack
 */

namespace Newspack;

use Newspack\Insights\Donation_Product_Classifier;
use Newspack\Insights\Subscribers_REST_Controller;

defined( 'ABSPATH' ) || exit;

/**
 * Subscribers section.
 */
class Insights_Section_Subscribers {

	/**
	 * Display label for this tab. Must match the React tab label.
	 *
	 * @var string
	 */
	const SECTION_NAME = 'Subscribers';

	/**
	 * Initialize. Loads Tab 6 classes and hooks the REST controller.
	 */
	public static function init() {
		if ( ! Insights_Wizard::is_enabled() ) {
			return;
		}
		self::load_dependencies();
		self::register_hooks();
	}

	/**
	 * Manually require the Tab 6 PHP files. Composer's classmap is
	 * regenerated by CI, but local-dev runs need explicit includes the
	 * same way other Insights section files are wired in
	 * `includes/class-newspack.php`.
	 *
	 * @return void
	 */
	private static function load_dependencies(): void {
		$base = NEWSPACK_ABSPATH . 'includes/wizards/insights/';
		include_once $base . 'storage/trait-reader-population.php';
		include_once $base . 'storage/class-storage-interface.php';
		include_once $base . 'storage/class-storage-detector.php';
		include_once $base . 'storage/class-hpos-storage.php';
		include_once $base . 'storage/class-legacy-storage.php';
		include_once $base . 'classifiers/class-donation-product-classifier.php';
		include_once $base . 'metrics/class-subscribers-metric.php';
		include_once $base . 'api/class-subscribers-rest-controller.php';
	}

	/**
	 * Register the Tab 6 REST route + delegate donation-classifier cache
	 * invalidation hooks.
	 *
	 * @return void
	 */
	public static function register_hooks(): void {
		add_action(
			'rest_api_init',
			function () {
				$controller = new Subscribers_REST_Controller();
				$controller->register_routes();
			}
		);
		Donation_Product_Classifier::register_hooks();
	}
}
